### ISSUE TITLE
failure starting cache install task

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nix-actions/cache-install#10]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/757125/187029072-fc290eff-f00f-4f15-9621-31b6b39cb7c0.png">

<img width="859" alt="image" src="https://user-images.githubusercontent.com/757125/187029096-539585c4-8a8b-49f1-a18e-52de7624c57a.png">

https://github.com/ComposableFi/composable/actions/runs/2937366959/workflow

**Comment by rikhuijzer** [comment]
I'm sorry, I'm going to close and lock this issue.

- The example is not a minimal reproducible example
- Images of code are not very useful.
- The project seems to be using this project together with Cachix which is likely to not work.
