### ISSUE TITLE
why would not gh cache of /nix/store would not work?

### ISSUE THREAD

**Issue by dzmitry-lahoda** [nix-actions/cache-install#11]
https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows

so I can just cache this?

i mean what is catch - may be add to readme

**Comment by rikhuijzer** [comment]
I'm sorry what is the question exactly?

**Comment by rikhuijzer** [comment]
Ah I now also re-read the title.

Using the default cache from GitHub won't work because `/nix/store` is read-only. One of the things that this `cache-install` project does is to handle those file permissions correctly.
